// Package onlineconf reads configuration files generated by OnlineConf.
//
// It opens indexed CDB files and maps them in the memory.
// If onlineconf-updater modifies them, they are automatically reopened.
package onlineconf

func loadModuleFromFile(filePath string) (*Module, error) {
	cdbFile, err := mmap.Open(filePath)
	defer cdbFile.Close()

	if err != nil {
		return nil, fmt.Errorf("Cant open filr %s: %w", filePath, err) // todo check %w works
	}

	module, err := NewModule(cdbFile)
	if err != nil {
		return nil, err
	}

	return module, nil
}
