// Package onlineconf reads configuration files generated by OnlineConf.
//
// It opens indexed CDB files and maps them in the memory.
// If onlineconf-updater modifies them, they are automatically reopened.
package onlineconf

import (
	"os"

	"github.com/grandecola/mmap"
)

func loadModuleFromFile(filePath string) (*Module, error) {
	file, err := os.OpenFile(filePath, os.O_RDONLY, 0)
	cdbFile, err := mmap.NewSharedFileMmap(file, 0, -1, 0)
	if err != nil {
		return nil, err
	}
	// defer file.Close()

	module, err := NewModule(cdbFile)
	if err != nil {
		return nil, err
	}

	return module, nil
}
